Remove unused include of rosbag2_cpp/typesupport_helpers.hpp
This header file was removed in Jazzy (rosbag2 release 0.26.10). Since
nothing seems to use this header file, let's remove it.

This fixes the following compile error:

    In file included from src/raw_to_bag.cpp:20:
    include/event_camera_tools/ros_compat.h:29:10: fatal error:
    rosbag2_cpp/typesupport_helpers.hpp: No such file or directory
       29 | #include <rosbag2_cpp/typesupport_helpers.hpp>
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Michal Sojka <michal.sojka@cvut.cz>